services:
  flutter_dev:
    build: .
    volumes:
      # Local files mapped 
      - .:/app
      - /opt/flutter:/opt/flutter # flutter SDK so we can do syntax highlighting in VSCode
      - ${PUB_CACHE}:${PUB_CACHE} # Docker cached volumes
      - flutter-build:/app/build
      - gradle-cache:/root/.gradle # Cache Gradle dependencies
      - android-cache:/root/.android # Cache Android SDK downloads
      - android-tools:/opt/android-tools
      - android-sdk-linux:/opt/android-sdk-linux
      - bash-history:/commandhistory
      - "/dev/bus/usb:/dev/bus/usb" # For physical device debugging
      - /tmp/.docker.xauth:/tmp/.docker.xauth
      - ./51-android-rules:/etc/udev/rules.d/51-android-rules # For physical device rules, specifically 51-android.rules

    ports:
      - 8080:8080

    # Environment variables are also set in .env file
    environment:
      - DISPLAY=host.docker.internal:0
      - HISTFILE=/commandhistory/.bash_history
      - PUB_CACHE=/home/${USER}/.pub-cache
      - XAUTHORITY=/tmp/.docker.xauth
      - DOCKER_STARTED_MARKER=/tmp/.docker_started

    privileged: true

    #    network_mode: "host" 
    # this is a dev container so we want to keep it alive
    #   we touch /tmp/.docker_started to keep track of when it started
    entrypoint: [ "/bin/bash", "-c", "make fix-permissions && tail -f /dev/null" ]

# Volumes managed by Docker that persists between container runs
volumes:
  flutter-build:
  gradle-cache:
  android-cache:
  android-tools:
  android-sdk-linux:
  bash-history:
