services:
  flutter_dev:
    build: .
    volumes:
      # Local files mapped 
      - .:/app
      - ./.devcontainer/etc/udev/rules.d:/etc/udev/rules.d # For physical device rules, specifically 51-android.rules
      - /opt/flutter:/opt/flutter # flutter SDK so we can do syntax highlighting in VSCode
      - ${PUB_CACHE}:${PUB_CACHE} # Docker cached volumes
      - flutter-build:/app/build
      - gradle-cache:/root/.gradle # Cache Gradle dependencies
      - android-cache:/root/.android # Cache Android SDK downloads
      - android-tools:/opt/android-tools
      - android-sdk-linux:/opt/android-sdk-linux
      - bash-history:/commandhistory
      - "/dev/bus/usb:/dev/bus/usb" # For physical device debugging
      - /tmp/.docker.xauth:/tmp/.docker.xauth

    ports:
      - 8080:8080

    environment:
      - DISPLAY=host.docker.internal:0
      - HISTFILE=/commandhistory/.bash_history
      - PUB_CACHE=${PUB_CACHE}
      - XAUTHORITY=/tmp/.docker.xauth

    privileged: true

    #    network_mode: "host" 
    tty: true
    stdin_open: true

# Volumes managed by Docker that persists between container runs
volumes:
  flutter-build:
  gradle-cache:
  android-cache:
  android-tools:
  android-sdk-linux:
  bash-history:
